spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-192-210-139.compute-1.amazonaws.com:5432/d32u60oq0lbdrk
    username: vljmjuucrfczmc
    password: 4b0961c154cf72329aa6ef4d076d4a7889f5c1fcf208f7822e37be8df4d96419
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  messages:
    always-use-message-format: true
server:
  port: